[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "momentum_train"
version = "0.1.7"
description = "Training module for momentum trader"
authors = [
  { name="Erik Veenhuis" },
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch==2.9.0",
    "numpy==2.3.4",
    "pandas==2.3.3",
    "scikit-learn==1.7.2",
    "PyYAML==6.0.3",
    "momentum_agent==0.1.7",
    "momentum_env==0.1.6",
    "momentum-core==0.1.0",
    "tensorboard==2.20.0",
    "wandb==0.22.3",
]

[project.optional-dependencies]
dev = [
    "black==25.9.0",
    "flake8==7.3.0",
    "isort==7.0.0",
    "mypy==1.18.2",
    "pytest==8.4.2",
    "pytest-cov>=7.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 128
target-version = ['py313']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra -q"
markers = [
    "integration: marks tests as integration tests",
    "unittest: marks tests as unit tests",
]

[tool.ruff]
line-length = 128

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = ["F841", "E501"]
