[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "momentum_live"
version = "0.1.0"
description = "Live trading for momentum strategy"
authors = [
  { name="Erik Veenhuis" },
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "momentum_agent==0.1.5",
    "momentum_env==0.1.5",
]

[project.optional-dependencies]
dev = [
    "black==25.1.0",
    "flake8==7.2.0",
    "isort==6.0.1",
    "pytest==8.3.5",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 128
target-version = ['py313']

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra -q"
